language: node_js

node_js:
  - "6"
  - "7"
  - "8"
  - "9"
  - "stable"

sudo: false

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - yarn lint:js
  - yarn lint:css
  - yarn test
  - yarn build:dev

notifications:
  email:
    on_failure: change

after_success:
  - yarn coveralls
