language: node_js

branches:
  only:
    - master

node_js:
  - "7"
  - "8"
  - "9"
  - "stable"

sudo: false

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - yarn build:dev
  - yarn lint:js
  - yarn lint:css
  - yarn test

notifications:
  email:
    on_failure: change
